/* An array of ACTIVE internal bot names */
export const BotNames = [
  "assault",
  "arenafighter",
  "arenafighterevent",
  "bear",
  "bossboar",
  "bossboarsniper",
  "bossbully",
  "bossgluhar",
  "bosskilla",
  "bossknight",
  "bosskojaniy",
  "bosskolontay",
  "bosspartisan",
  "bosssanitar",
  "bosstagilla",
  "bosszryachiy",
  "exusec",
  "followerboarclose2",
  "followerboarclose1",
  "followerboar",
  "followerbirdeye",
  "followerbigpipe",
  "followerbully",
  "followergluharassault",
  "followergluharscout",
  "followergluharsecurity",
  //"followergluharsnipe",
  "followerkojaniy",
  "followerkolontayassault",
  "followerkolontaysecurity",
  "followersanitar",
  "followertagilla",
  "followerzryachiy",
  "gifter",
  "pmcbear",
  "pmcbot",
  "pmcusec",
  "marksman",
  "sectantoni",
  "sectantpredvestnik",
  "sectantpriest",
  "sectantprizrak",
  "sectantwarrior",
  "shooterbtr",
  // "assaultgroup",
  // "crazyassaultevent",
  // "cursedassault",

  // "infectedassault",
  // "infectedcivil",
  // "infectedlaborant",
  // "infectedpmc",
  // "infectedtagilla",
  // "peacefulzryachiyevent",
  // "peacemaker.json",
  // "ravangezryachiyevent",
  // "followertest",
  // "skier",
  // "spiritspring",
  // "spiritwinter",
  // "test",
  "usec"
];

/* A list of EFT internal bot names with common name */
export enum BotCommonNames {
  "assault" = "Scav",
  "arenafighter" = "Arena Scav",
  "arenafighterevent" = "Smuggler",
  "bear" = "Bear PMC",
  "bossboar" = "Kaban",
  "bossboarsniper" = "Boar sniper guard",
  "bossbully" = "Reshala",
  "bossgluhar" = "Gluhkar",
  "bosskilla" = "Killa",
  "bossknight" = "Knight",
  "bosskojaniy" = "Shturman",
  "bosskolontay" = "Kolontay",
  "bosspartisan" = "Partisan",
  "bosssanitar" = "Sanitar",
  "bosstagilla" = "Tagilla",
  "bosszryachiy" = "Zryachiy",
  "exusec" = "Rogue",
  "followerboarclose2" = "Basmach",
  "followerboarclose1" = "Gus",
  "followerboar" = "Boar guard",
  "followerbirdeye" = "Birdeye",
  "followerbigpipe" = "Big pipe",
  "followerbully" = "Reshala guard",
  "followergluharassault" = "Gluhar assault",
  "followergluharscout" = "Gluhar scout",
  "followergluharsecurity" = "Gluhar security",
  "followergluharsnipe" = "Gluhar sniper",
  "followerkojaniy" = "Shturman guard",
  "followerkolontayassault" = "Kolontay assault",
  "followerkolontaysecurity" = "Kolontay security",
  "followersanitar" = "Sanitar guard",
  "followertagilla" = "Tagilla guard",
  "followerzryachiy" = "Zryachiy guard",
  "gifter" = "Santa",
  "pmcbear" = "Bear Raider",
  "pmcbot" = "Raider",
  "pmcusec" = "Usec Raider",
  "marksman" = "Marksman",
  "sectantoni" = "Cultist Oni",
  "sectantpredvestnik" = "Cultist Predvestnik",
  "sectantpriest" = "Cultist Priest",
  "sectantprizrak" = "Culstist Prizrak",
  "sectantwarrior" = "Cultist Warrior",
  "shooterbtr" = "BTR",
  "usec" = "Usec PMC"
};