export enum WildSpawnType {
  marksman = "marksman",
  assault = "assault",
  bossTest = "bossTest",
  bossBully = "bossBully",
  followerTest = "followerTest",
  followerBully = "followerBully",
  bossKilla = "bossKilla",
  bossKojaniy = "bossKojaniy",
  followerKojaniy = "followerKojaniy",
  pmcbot = "pmcBot",
  cursedAssault = "cursedAssault",
  bossGluhar = "bossGluhar",
  followerGluharAssault = "followerGluharAssault",
  followerGluharSecurity = "followerGluharSecurity",
  followerGluharScout = "followerGluharScout",
  followerGluharSnipe = "followerGluharSnipe",
  followerSanitar = "followerSanitar",
  bossSanitar = "bossSanitar",
  //test = "test",
  //assaultGroup = "assaultGroup",
  sectantWarrior = "sectantWarrior",
  sectantPriest = "sectantPriest",
  bossTagilla = "bossTagilla",
  followerTagilla = "followerTagilla",
  exUsec = "exUsec",
  gifter = "gifter",
  bossKnight = "bossKnight",
  followerBigPipe = "followerBigPipe",
  followerBirdEye = "followerBirdEye",
  bossZryachiy = "bossZryachiy",
  followerZryachiy = "followerZryachiy",
  bossBoar = "bossBoar",
  followerBoar = "followerBoar",
  arenaFighter = "arenaFighter",
  arenaFighterEvent = "arenaFighterEvent",
  bossBoarSniper = "bossBoarSniper",
  crazyAssaultEvent = "crazyAssaultEvent",
  //"peacefullZryachiyEvent",
  //"sectactPriestEvent",
  //"ravangeZryachiyEvent",
  followerBoarClose1 = "followerBoarClose1",
  followerBoarClose2 = "followerBoarClose2",
  bossKolontay = "bossKolontay",
  followerKolontayAssault = "followerKolontayAssault",
  followerKolontaySecurity = "followerKolontaySecurity",
  shooterBTR = "shooterBTR",
  bossPartisan = "bossPartisan",
  //"spiritWinter",
  //"spiritSpring",
  //"peacemaker",
  pmcBEAR = "pmcBEAR",
  pmcUSEC = "pmcUSEC",
  //"skier",
  //sectantPredvestnik = "sectantPredvestnik = 57",
  //sectantPrizrak="sectantPrizrak",
  //sectantOni="sectantOni",
  //"infectedAssault",
  //"infectedPmc",
  //"infectedCivil",
  //"infectedLaborant",
  //"infectedTagilla",
  bossTagillaAgro = "bossTagillaAgro",
  bossKillaAgro = "bossKillaAgro",
  tagillaHelperAgro = "tagillaHelperAgro"
}

export const WildSpawnTypeList: string[] =
  [
    "marksman",
    "assault",
    "bossTest",
    "bossBully",
    "followerTest",
    "followerBully",
    "bossKilla",
    "bossKojaniy",
    "followerKojaniy",
    "pmcBot",
    "cursedAssault",
    "bossGluhar",
    "followerGluharAssault",
    "followerGluharSecurity",
    "followerGluharScout",
    "followerGluharSnipe",
    "followerSanitar",
    "bossSanitar",
    "test",
    "assaultGroup",
    "sectantWarrior",
    "sectantPriest",
    "bossTagilla",
    "followerTagilla",
    "exUsec",
    "gifter",
    "bossKnight",
    "followerBigPipe",
    "followerBirdEye",
    "bossZryachiy",
    "followerZryachiy",
    "bossBoar = 32",
    "followerBoar",
    "arenaFighter",
    "arenaFighterEvent",
    "bossBoarSniper",
    "crazyAssaultEvent",
    "peacefullZryachiyEvent",
    "sectactPriestEvent",
    "ravangeZryachiyEvent",
    "followerBoarClose1",
    "followerBoarClose2",
    "bossKolontay",
    "followerKolontayAssault",
    "followerKolontaySecurity",
    "shooterBTR",
    "bossPartisan",
    "spiritWinter",
    "spiritSpring",
    "peacemaker",
    "pmcBEAR",
    "pmcUSEC",
    "skier",
    "sectantPredvestnik = 57",
    "sectantPrizrak",
    "sectantOni",
    "infectedAssault",
    "infectedPmc",
    "infectedCivil",
    "infectedLaborant",
    "infectedTagilla",
    "bossTagillaAgro",
    "bossKillaAgro",
    "tagillaHelperAgro"
  ];